name-template: 'v$RESOLVED_VERSION ⚡'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '💥 Breaking Changes'
    label: 'major'

  - title: '⚠️ Big Changes'
    label: 'minor'

  - title: '🚀 Features'
    label: 'feature'

  - title: '🐛 Bug Fixes'
    label: 'fix'

  - title: '🧰 Maintenance'
    label: 'chore'

  - title: '⬆️ Dependencies'
    collapse-after: 3
    label: 'dependencies'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'chore'
    branch:
      - '/chore\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
  - label: 'feature'
    branch:
      - '/feat\/.+/'
  - label: 'dependencies'
    branch:
      - '/renovate\/.+/'

template: |
  ## Changes

  $CHANGES
